auto_mode: true
capture:
  fps: 5
  fullscreen:
    height: 1440
    width: 3440
  mode: fullscreen
  roi:
    enabled: false
    h: 1440
    w: 3440
    x: 0
    y: 0
  window:
    fallback_to_fullscreen: true
    partial_match: true
    process_name: WorldOfTanks.exe
control:
  key_press_duration: 50
  mouse_sensitivity: 1.0
  safe_mode: true
